-- 采购调价单主表 / 明细表（公共）
-- 单号规则：TJ- + yyyyMMdd + 5位流水，租户内唯一

CREATE TABLE IF NOT EXISTS `purchase_price_adjust` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `bill_no` varchar(64) NOT NULL COMMENT '单据号 TJ-yyyyMMdd#####',
  `adjust_type` varchar(32) NOT NULL COMMENT '调价类型 archive/warehouse/department',
  `supplier_id` bigint(20) DEFAULT NULL COMMENT '供应商ID',
  `bill_date` date DEFAULT NULL COMMENT '制单日期',
  `contact_name` varchar(64) DEFAULT NULL COMMENT '联系人',
  `contact_phone` varchar(32) DEFAULT NULL COMMENT '联系方式',
  `bill_status` char(1) DEFAULT '0' COMMENT '单据状态 0未提交 1未审核 2已审核',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '审核人',
  `audit_date` datetime DEFAULT NULL COMMENT '审核日期',
  `print_by` varchar(64) DEFAULT NULL COMMENT '打印人',
  `print_date` datetime DEFAULT NULL COMMENT '打印日期',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志 0正常 1删除',
  `tenant_id` varchar(36) DEFAULT NULL COMMENT '租户ID',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_price_adjust_tenant_bill_no` (`tenant_id`, `bill_no`),
  KEY `idx_price_adjust_bill_date` (`bill_date`),
  KEY `idx_price_adjust_supplier` (`supplier_id`),
  KEY `idx_price_adjust_status` (`bill_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购调价单主表';

CREATE TABLE IF NOT EXISTS `purchase_price_adjust_entry` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `parent_id` bigint(20) NOT NULL COMMENT '主表ID',
  `bill_no` varchar(64) DEFAULT NULL COMMENT '单据号冗余',
  `line_no` int DEFAULT NULL COMMENT '行号',
  `material_id` bigint(20) NOT NULL COMMENT '耗材ID',
  `material_code` varchar(64) DEFAULT NULL COMMENT '产品编码',
  `material_name` varchar(200) DEFAULT NULL COMMENT '产品名称',
  `speci` varchar(200) DEFAULT NULL COMMENT '规格',
  `model` varchar(200) DEFAULT NULL COMMENT '型号',
  `unit_name` varchar(64) DEFAULT NULL COMMENT '单位',
  `old_price` decimal(18,6) DEFAULT NULL COMMENT '原价',
  `new_price` decimal(18,6) DEFAULT NULL COMMENT '现价',
  `finance_class` varchar(100) DEFAULT NULL COMMENT '财务分类',
  `manufacturer` varchar(200) DEFAULT NULL COMMENT '生产厂家',
  `reg_no` varchar(100) DEFAULT NULL COMMENT '注册证号',
  `reg_valid_date` varchar(64) DEFAULT NULL COMMENT '注册证有效期',
  `pack_speci` varchar(200) DEFAULT NULL COMMENT '包装规格',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志',
  `tenant_id` varchar(36) DEFAULT NULL COMMENT '租户ID',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_price_adjust_entry_parent` (`parent_id`),
  KEY `idx_price_adjust_entry_material` (`material_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购调价单明细';
