-- 说明：登录用户 sys_user.customer_id / Token 已与 TenantEnum 一致（如 hengsui-third-001），
-- 但 fd_warehouse / fd_department 仍写旧 tenant_id（如历史 UUID）时，列表会为空。
-- 1) 先核对：
--    SELECT customer_id, tenant_key FROM sb_customer WHERE customer_id = 'hengsui-third-001';
--    SELECT DISTINCT tenant_id FROM fd_warehouse LIMIT 20;
--    SELECT DISTINCT tenant_id FROM fd_department LIMIT 20;
-- 2) 若确认仅存在「旧 id → 新 id」一对映射，可执行（请替换 OLD_TENANT_ID）：
--
-- UPDATE fd_warehouse SET tenant_id = 'hengsui-third-001' WHERE tenant_id = 'OLD_TENANT_ID';
-- UPDATE fd_department SET tenant_id = 'hengsui-third-001' WHERE tenant_id = 'OLD_TENANT_ID';
--
-- 应用侧已在 Mapper 中增加「同 sb_customer.tenant_key 的其它 customer_id」兼容查询，避免仅因迁移期不一致导致列表为空。
