-- 高值追溯单表
CREATE TABLE `gz_traceability` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `trace_no` varchar(50) NOT NULL COMMENT '追溯单号（唯一）',
  `medical_record_no` varchar(50) DEFAULT NULL COMMENT '病历号',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名',
  `patient_sex` varchar(10) DEFAULT NULL COMMENT '患者性别',
  `patient_age` int(11) DEFAULT NULL COMMENT '患者年龄',
  `hospital_number` varchar(50) DEFAULT NULL COMMENT '住院号',
  `ward` varchar(50) DEFAULT NULL COMMENT '病区',
  `ward_no` varchar(50) DEFAULT NULL COMMENT '病房号',
  `bed_no` varchar(50) DEFAULT NULL COMMENT '病床号',
  `apply_dept_id` bigint(20) DEFAULT NULL COMMENT '申请科室ID',
  `exec_dept_id` bigint(20) DEFAULT NULL COMMENT '执行科室ID',
  `hospital_date` date DEFAULT NULL COMMENT '住院日期',
  `contact_phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `contact_address` varchar(200) DEFAULT NULL COMMENT '联系地址',
  `chief_surgeon` varchar(50) DEFAULT NULL COMMENT '主刀医生',
  `surgery_date` date DEFAULT NULL COMMENT '手术日期',
  `surgery_name` varchar(200) DEFAULT NULL COMMENT '手术名称',
  `admission_diagnosis` varchar(500) DEFAULT NULL COMMENT '入院诊断',
  `surgery_id` varchar(50) DEFAULT NULL COMMENT '手术ID',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `order_status` int(11) DEFAULT 1 COMMENT '单据状态（1=未审核，2=已审核）',
  `audit_date` date DEFAULT NULL COMMENT '审核日期',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '审核人',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志（0代表存在 2代表删除）',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trace_no` (`trace_no`),
  KEY `idx_medical_record_no` (`medical_record_no`),
  KEY `idx_hospital_number` (`hospital_number`),
  KEY `idx_order_status` (`order_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='高值追溯单表';

-- 高值追溯单明细表
CREATE TABLE `gz_traceability_entry` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `parent_id` bigint(20) NOT NULL COMMENT '追溯单ID',
  `material_id` bigint(20) DEFAULT NULL COMMENT '耗材ID',
  `inventory_id` bigint(20) DEFAULT NULL COMMENT '库存ID',
  `material_name` varchar(200) DEFAULT NULL COMMENT '耗材名称',
  `specification` varchar(200) DEFAULT NULL COMMENT '规格',
  `model` varchar(200) DEFAULT NULL COMMENT '型号',
  `unit` varchar(50) DEFAULT NULL COMMENT '单位',
  `quantity` decimal(10,2) DEFAULT NULL COMMENT '数量',
  `charge_price` decimal(10,2) DEFAULT NULL COMMENT '收费价',
  `batch_no` varchar(100) DEFAULT NULL COMMENT '批号',
  `expiry_date` date DEFAULT NULL COMMENT '有效期',
  `in_hospital_code` varchar(100) DEFAULT NULL COMMENT '院内码',
  `manufacturer` varchar(200) DEFAULT NULL COMMENT '生产厂家',
  `supplier` varchar(200) DEFAULT NULL COMMENT '供应商',
  `certificate_no` varchar(100) DEFAULT NULL COMMENT '注册证号',
  `billing_follow` char(1) DEFAULT '0' COMMENT '跟台标识（0=否，1=是）',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志（0代表存在 2代表删除）',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_material_id` (`material_id`),
  KEY `idx_in_hospital_code` (`in_hospital_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='高值追溯单明细表';
