-- 批次表：入库审核时根据批次号生成批次记录，用于追溯
-- 批次号唯一，同一批次号只插入一次；库存表、单据明细表通过 batch_no 关联

DROP TABLE IF EXISTS `stk_batch`;
CREATE TABLE `stk_batch` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '批次对象表ID',
  `batch_no` varchar(100) NOT NULL COMMENT '批次号，存到库存表和单据明细表的批次字段',
  `material_id` bigint(20) DEFAULT NULL COMMENT '产品档案ID',
  `material_code` varchar(64) DEFAULT NULL COMMENT '产品档案编码',
  `material_name` varchar(200) DEFAULT NULL COMMENT '名称',
  `speci` varchar(200) DEFAULT NULL COMMENT '规格',
  `model` varchar(100) DEFAULT NULL COMMENT '型号',
  `unit_id` bigint(20) DEFAULT NULL COMMENT '单位ID',
  `unit_name` varchar(50) DEFAULT NULL COMMENT '单位名称',
  `unit_price` decimal(18,2) DEFAULT NULL COMMENT '单价',
  `batch_number` varchar(100) DEFAULT NULL COMMENT '批号',
  `end_time` date DEFAULT NULL COMMENT '有效期',
  `begin_time` date DEFAULT NULL COMMENT '生产日期',
  `sterilize_batch_no` varchar(100) DEFAULT NULL COMMENT '灭菌批号',
  `sterilize_end_time` date DEFAULT NULL COMMENT '灭菌有效期',
  `use_times` int(11) DEFAULT NULL COMMENT '使用次数/人次',
  `main_barcode` varchar(100) DEFAULT NULL COMMENT '主条码',
  `sub_barcode` varchar(100) DEFAULT NULL COMMENT '辅条码',
  `register_no` varchar(100) DEFAULT NULL COMMENT '注册证号',
  `permit_no` varchar(100) DEFAULT NULL COMMENT '生产许可证号',
  `factory_id` bigint(20) DEFAULT NULL COMMENT '生产厂家ID',
  `factory_code` varchar(64) DEFAULT NULL COMMENT '生产厂家编码',
  `factory_name` varchar(200) DEFAULT NULL COMMENT '生产厂家名称',
  `supplier_id` bigint(20) DEFAULT NULL COMMENT '供应商ID',
  `supplier_code` varchar(64) DEFAULT NULL COMMENT '供应商编码',
  `supplier_name` varchar(200) DEFAULT NULL COMMENT '供应商名称',
  `warehouse_id` bigint(20) DEFAULT NULL COMMENT '仓库ID',
  `warehouse_code` varchar(64) DEFAULT NULL COMMENT '仓库编码',
  `warehouse_name` varchar(200) DEFAULT NULL COMMENT '仓库名称',
  `department_id` bigint(20) DEFAULT NULL COMMENT '科室ID',
  `department_code` varchar(64) DEFAULT NULL COMMENT '科室编码',
  `department_name` varchar(200) DEFAULT NULL COMMENT '科室名称',
  `storeroom_id` bigint(20) DEFAULT NULL COMMENT '库房分类ID',
  `storeroom_code` varchar(64) DEFAULT NULL COMMENT '库房分类编码',
  `storeroom_name` varchar(200) DEFAULT NULL COMMENT '库房分类名称',
  `finance_category_id` bigint(20) DEFAULT NULL COMMENT '财务分类ID',
  `finance_category_code` varchar(64) DEFAULT NULL COMMENT '财务分类编码',
  `finance_category_name` varchar(200) DEFAULT NULL COMMENT '财务分类名称',
  `batch_source` varchar(32) DEFAULT NULL COMMENT '批次产生方式：采购入库/仓库盘盈/科室盘盈等',
  `bill_id` bigint(20) DEFAULT NULL COMMENT '单据主表ID',
  `bill_no` varchar(64) DEFAULT NULL COMMENT '单据号',
  `entry_id` bigint(20) DEFAULT NULL COMMENT '单据明细ID',
  `in_code_detail_id` bigint(20) DEFAULT NULL COMMENT '院内码明细ID',
  `audit_time` datetime DEFAULT NULL COMMENT '单据审核时间',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '单据审核人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建人',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新人',
  `del_flag` int(1) NOT NULL DEFAULT 0 COMMENT '删除标志（0=正常，1=已删除）',
  `del_time` datetime DEFAULT NULL COMMENT '删除时间',
  `del_by` varchar(64) DEFAULT NULL COMMENT '删除人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_no` (`batch_no`),
  KEY `idx_material_id` (`material_id`),
  KEY `idx_warehouse_id` (`warehouse_id`),
  KEY `idx_bill_id` (`bill_id`),
  KEY `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='批次表';

-- 库存表增加批次对象表ID，用于追溯
ALTER TABLE `stk_inventory` ADD COLUMN `batch_id` bigint(20) DEFAULT NULL COMMENT '批次对象表ID（关联 stk_batch.id）' AFTER `batch_no`;
ALTER TABLE `stk_inventory` ADD KEY `idx_batch_id` (`batch_id`);
